out_dir: results
metric_best: accuracy
wandb:
  use: False
  project: ppa
dataset:
  format: PyG-Dataset
  name: MyLocalPPA_C
  raw_filename: "train.json.gz"
  task: graph
  task_type: classification
  transductive: False
  node_encoder: False
  edge_encoder: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: default
  layers_mp: 4
  layer_type: gatedgcn
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 512 
  batchnorm: True
  act: relu
  dropout: 0.15
  agg: mean
  normalize_adj: False
  ffn: False
  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0003
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10